name: "Release"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

concurrency:
  # Same group as prerelease
  group: publish
  cancel-in-progress: false

jobs:

  # This gets the commit message because workflow dispatch doesnt set: github.event.head_commit.message
  pre-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      commit-message: ${{ steps.step1.outputs.commit-message }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100

      # Get the commit message, workflow_dispatch doesn't contain it so we need to get it through git cli
      - id: step1
        run: |
          if [ -n "${{ github.event.head_commit.message }}" ]
          then
            echo "commit-message=${{ github.event.head_commit.message }}" | head -n 1 >> "$GITHUB_OUTPUT"
          else
            commit_message=$(git log -1 --pretty=%B | head -n 1)
            echo "commit-message=$commit_message" >> "$GITHUB_OUTPUT"
          fi

      - name: Debug commit message
        run: |
          echo "Commit message: ${{ steps.step1.outputs.commit-message }}"

  Build-Publish:
    name: Build-Publish
    needs: pre-ci
    if: "!startsWith(needs.pre-ci.outputs.commit-message, '[SKIP CI]') && startsWith(needs.pre-ci.outputs.commit-message, '[release]') && github.repository == 'subquery/query-subgraph'"
    runs-on: ubuntu-latest
    steps:
      #Check out
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn

      - name: build
        run: yarn build

      #Publish to npm and github releases
      - name: Publish subgraph-query
        uses: ./.github/actions/create-release
        with:
          package-path: .
          repo-token: ${{ secrets.REPO_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
